add a section on how to rollback the database
gpodder/gpodder.github.io pull request #41
Opened 2022-07-28 16:11 UTC by elelay

2022-07-29 19:49 UTC, auouymous requested changes

2022-07-29 19:49 UTC, auouymous commented on docs/user-manual.md
> +The timestamp can be decoded on macOS and Linux using `date -d @xxxxxxxxxx`. Be sure to take the bigest
`bigest` should be `biggest`.

But there is no need to decode `xxxxxxxxxx` with `date`. The largest positive value is always the newest file. Files also have timestamps and all file managers should have a mode to display the timestamp, which would match the value returned by `date`.

2022-07-29 19:49 UTC, auouymous commented on docs/user-manual.md
> + 3. you will lose some changes made after the upgrade (added podcasts), but downloaded episodes should be found again.
> ... but downloaded episodes should be found again `after an update`.

An update would be needed to add any new episodes back into database before downloaded files would be found.

2022-07-29 21:04 UTC, elelay commented on docs/user-manual.md
> + 3. you will lose some changes made after the upgrade (added podcasts), but downloaded episodes should be found again.
also I'm not sure that episodes downloaded by youtube-dl and assembled would be found again, but let's hope they would.

2022-07-29 22:16 UTC, auouymous requested changes

2022-07-29 22:16 UTC, auouymous commented on docs/user-manual.md
> +the value returned by `date`.
I didn't mean to tell the user that. Mentioning the `date` or `date -d @xxxxxxxxxx` commands is too much information for most users. All they need to know is that the file with the highest `xxxxxxxxxx` value is the newest. Something like:

```
The file with largest `xxxxxxxxxx` timestamp number is the newest, for any given `VERSION`.
Be sure to use the previous version with newest timestamp if you have dipped in
and out of the new release.
```

To replace both paragraphs in all 6 lines.

2022-07-29 22:21 UTC, auouymous commented on docs/user-manual.md
> + 3. you will lose some changes made after the upgrade (added podcasts), but downloaded episodes should be found again.
Any youtube episode (youtube-dl or not) will fail to find downloaded files because the youtube feed doesn't have filenames. Maybe we should mention that any downloaded youtube episodes will not be found. And there currently is no way to make gpodder find them, short of downloading the episode again. But at least the re-download will take care of the existing file, so the user doesn't need to manually clean up.

2022-07-30 15:30 UTC, elelay commented on docs/user-manual.md
> +the value returned by `date`.
ok, I get it now

2022-07-31 04:24 UTC, merged

2022-07-31 04:25 UTC, auouymous commented
Thanks for writing this.