Added command on sync documentation
gpodder/gpodder.github.io pull request #56
Opened 2024-12-05 14:39 UTC by reactorcoremeltdown

A documentation counterpart for https://github.com/gpodder/gpodder/pull/1676

2024-12-21 18:29 UTC, thp commented on docs/extensions/commandonsync.md
> +One might want to run an external program when all podcast episodes get synchronized to external database (refresh a player's database or enqueue the episode, download episode statistics, run other d
```suggestion
One might want to run an external program when all podcast episodes get synchronized to external database (refresh a player's database or enqueue the episode, download episode statistics, run other device-related program like Last.FM scrobbler, etc.). This extension makes it possible to execute any command.
```

2024-12-21 18:30 UTC, thp commented on docs/extensions/commandonsync.md
> +`$GPODDER_HOME/Settings.json` to refine your command.
```suggestion
If the command is a bit long, write a wrapper script. You can also directly edit
`$GPODDER_HOME/Settings.json` to refine your command.
```

2024-12-21 18:30 UTC, thp commented on docs/extensions/commandonsync.md
> +zenity --info --width=600 --text="All episodes syncrhonized"
```suggestion
zenity --info --width=600 --text="All episodes synchronised"
```

2024-12-21 18:31 UTC, thp requested changes
Typos and style corrections.

2024-12-26 13:31 UTC, reactorcoremeltdown commented
Committed suggested changes. Thank you very much for patience!

2025-02-03 21:30 UTC, merged

2025-02-03 21:31 UTC, elelay commented
thanks for your contribution to gPodder :-)